jiehuo/config/routes.rb
Iknow::Application.routes.draw do



   #用户系统模块
  devise_for :users, :controllers => {:passwords => :devise_passwords,:invitations=>:devise_invitations,:sessions=>:devise_sessions} do
    #密码重置后跳转页面
    match '/users/password/reset_pw_success', :to => 'devise_passwords#reset_pw_success'
    #密码重置邮件发送成功后跳转页面
    match '/users/password/reset_pw_send_mail_ok', :to => 'devise_passwords#reset_pw_send_mail_ok'


  end

  #注册验证码路由
  captcha_route

  get "user_profile/basic"

  root :to => 'home#index'
  get "home/index"

  match '/follow/:id', :to => 'user_profile#follow#:id', :as => 'follow'
  match '/unfollow/:id', :to => 'user_profile#unfollow#:id', :as => 'unfollow'
  match '/unconcern/:id', :to => 'user_profile#unconcern#:id', :as => 'unconcern'
  match '/projects/follow/:id', :to => 'projects#follow#:id', :as => 'follow_project'
  match '/an_answer_comments/:id', :to => 'comments#an_answer_comments#:id', :as => 'comments'
  match '/people/follow_project/:project_id', :to => 'people#follow_project#:project_id', :as => 'people_follow_project'
  match '/people/unfollow_project/:project_id', :to => 'people#unfollow_project#:project_id', :as => 'people_unfollow_project'
  match '/people/collect_the_ask/:ask_id',:to=>'people#collect_the_ask#:ask_id',:as => 'people_collect_the_ask'
  match '/people/uncollect_the_ask/:ask_id',:to=>'people#uncollect_the_ask#:ask_id',:as => 'people_uncollect_the_ask'
  match '/people/add_as_classmate/:user_id',:to=>'people#add_as_classmate#:user_id',:as => 'people_add_as_classmate'
  match '/people/subtract_the_classmate/:user_id',:to=>'people#subtract_the_classmate#:user_id',:as => 'people_subtract_the_classmate'

  match '/register', :to => 'user_sessions#register'
  match '/user_profile/basic', :to => 'user_profile#basic'
  match '/user_profile/passwd', :to => 'user_profile#passwd'
  match '/user_profile/user_avatar', :to => 'user_profile#user_avatar'

  match '/people/more_set_asks/:ask_id/:id',:to=>'people#more_set_asks#:ask_id#:id'
  match '/people/more_answered_asks/:ask_id/:id',:to=>'people#more_answered_asks#:ask_id#:id'
  match '/people/more_favorites_asks/:ask_id/:id',:to=>'people#more_favorites_asks#:ask_id#:id'

  match '/people/answered_asks/:id',:to=>'people#answered_asks#:id'
  match '/people/favorites_asks/:id',:to=>'people#favorites_asks#:id'
  match '/ask/hide_ask/:id',:to=>'asks#hide_ask#:id'

  #match '/asks', :to => 'home#index'
  resources :comments, :answers, :asks
  resources :people
  resources :projects #网站端project模块

  resource :user_sessions, :member => {:register => :post}

  get "interest_users/get_interest_users"

  #CSM下的路由，这些路由进入网站后台
  namespace :cms do
    resources :domains, :schools, :projects, :sections
    resources :users do
      collection do
        post :school_ajax
      end
    end
  end

#-------------------------

#ask.js中使用到
  match ':controller(/:action(/:id(.:format)))'


end

jiehuo/app/models/cms.rb
module Cms
  def self.table_name_prefix
    'cms_'
  end
end

jiehuo/app/controllers/cms/areas_controller.rb
# coding: UTF-8
class Cms::AreasController < ApplicationController
  # GET /cms/areas
  # GET /cms/areas.json
  def index
    @areas = Area.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @areas }
    end
  end

  # GET /cms/areas/1
  # GET /cms/areas/1.json
  def show
    @area = Area.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @area }
    end
  end

  # GET /cms/areas/new
  # GET /cms/areas/new.json
  def new
    @area = Area.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @area }
    end
  end

  # GET /cms/areas/1/edit
  def edit
    @area = Area.find(params[:id])
  end

  # POST /cms/areas
  # POST /cms/areas.json
  def create
    @area = Area.new(params[:area])

    respond_to do |format|
      if @area.save
        format.html { redirect_to cms_area_path(@area), notice: 'Area was successfully created.' }
        format.json { render json: cms_area_path(@area), status: :created, location: @area }
      else
        format.html { render action: "new" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cms/areas/1
  # PUT /cms/areas/1.json
  def update
    @area = Area.find(params[:id])

    respond_to do |format|
      if @area.update_attributes(params[:area])
        format.html { redirect_to cms_area_path(@area), notice: 'Area was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cms/areas/1
  # DELETE /cms/areas/1.json
  def destroy
    @area = Area.find(params[:id])
    @area.destroy

    respond_to do |format|
      format.html { redirect_to cms_areas_url }
      format.json { head :ok }
    end
  end
end

jiehuo/app/controllers/cms/domains_controller.rb
# coding: UTF-8
class Cms::DomainsController < ApplicationController
  # GET /cms/domains
  # GET /cms/domains.json
  def index
    @cms_domains = Domain.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cms_domains }
    end
  end

  # GET /cms/domains/1
  # GET /cms/domains/1.json
  def show
    @cms_domain = Domain.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cms_domain }
    end
  end

  # GET /cms/domains/new
  # GET /cms/domains/new.json
  def new
    @cms_domain = Domain.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cms_domain }
    end
  end

  # GET /cms/domains/1/edit
  def edit
    @cms_domain = Domain.find(params[:id])
  end

  # POST /cms/domains
  # POST /cms/domains.json
  def create

    @cms_domain = Domain.new(params[:domain])#A此地cms_domain修改为domain

    respond_to do |format|
      if @cms_domain.save
        format.html { redirect_to cms_domain_path(@cms_domain), notice: 'Domain was successfully created.' } #A此地@cms_domain修改为cms_domain_path(@cms_domain)
        format.json { render json: @cms_domain, status: :created, location: @cms_domain }
      else
        format.html { render action: "new" }
        format.json { render json: @cms_domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cms/domains/1
  # PUT /cms/domains/1.json
  def update
    @cms_domain = Domain.find(params[:id])

    respond_to do |format|
      if @cms_domain.update_attributes(params[:domain])#A此地cms_domain修改为domain
        format.html { redirect_to cms_domain_path, notice: 'Domain was successfully updated.' } #A此地@cms_domain修改为cms_domain_path
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cms_domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cms/domains/1
  # DELETE /cms/domains/1.json
  def destroy
    @cms_domain = Domain.find(params[:id])
    @cms_domain.destroy

    respond_to do |format|
      format.html { redirect_to cms_domains_url }
      format.json { head :ok }
    end
  end
end

jiehuo/app/controllers/cms/projects_controller.rb
class Cms::ProjectsController < ApplicationController
  # GET /cms/projects
  # GET /cms/projects.json
  def index
    @projects = Project.paginate(:page => params[:page], :per_page => 2, :order => 'updated_at DESC')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /cms/projects/1
  # GET /cms/projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /cms/projects/new
  # GET /cms/projects/new.json
  def new
    @project = Project.new
    @domain = Domain.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /cms/projects/1/edit
  def edit
    @project = Project.find(params[:id])
    @domain = Domain.all
  end

  # POST /cms/projects
  # POST /cms/projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to cms_project_path(@project), notice: 'Project was successfully created.' }
        format.json { render json: cms_project_path(@project), status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cms/projects/1
  # PUT /cms/projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to cms_project_path(@project), notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cms/projects/1
  # DELETE /cms/projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to cms_projects_url }
      format.json { head :ok }
    end
  end
end

jiehuo/app/controllers/cms/schools_controller.rb
# coding: UTF-8
class Cms::SchoolsController < ApplicationController
# GET /cms/schools
# GET /cms/schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /cms/schools/1
  # GET /cms/schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /cms/schools/new
  # GET/cms/schools/new.json
  def new



    @provinces = get_redis_provinces().map { |u| [u["province"], u["provinceid"]] }


    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /cms/schools/1/edit
  def edit
    @provinces = get_redis_provinces().map { |u| [u["province"], u["provinceid"]] }

    @school = School.find(params[:id])
  end

  # POST /cms/schools
  # POST /cms/schools.json
  def create
    @school = School.new(params[:school])
    @school.creator = "sys_creator"
    @school.modifier = "sys_modifier"
    respond_to do |format|
      if @school.save
        format.html { redirect_to cms_school_path(@school), notice: 'School was successfully created.' }
        format.json { render json: cms_school_path(@school), status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cms/schools/1
  # PUT /cms/schools/1.json
  def update
    @school = School.find(params[:id])
    params[:school][:creator] = "sys_creator"
    params[:school][:modifier] = "sys_modifier"
    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to cms_school_path(@school), notice: 'School was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cms/schools/1
  # DELETE /cms/schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to cms_schools_url }
      format.json { head :ok }
    end
  end
end

jiehuo/app/controllers/cms/sections_controller.rb
class Cms::SectionsController < ApplicationController
  # GET /cms/sections
  # GET /cms/sections.json
  def index
    @sections = Section.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sections }
    end
  end

  # GET /cms/sections/1
  # GET /cms/sections/1.json
  def show
    @section = Section.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @section }
    end
  end

  # GET /cms/sections/new
  # GET /cms/sections/new.json
  def new
    @section = Section.new
    @project = Project.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @section }
    end
  end

  # GET /cms/sections/1/edit
  def edit
    @section = Section.find(params[:id])
    @project = Project.all
  end

  # POST /cms/sections
  # POST /cms/sections.json
  def create
    @section = Section.new(params[:section])

    respond_to do |format|
      if @section.save
        format.html { redirect_to cms_section_path(@section), notice: 'Section was successfully created.' }
        format.json { render json: cms_section_path(@section), status: :created, location: @section }
      else
        format.html { render action: "new" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cms/sections/1
  # PUT /cms/sections/1.json
  def update
    @section = Section.find(params[:id])

    respond_to do |format|
      if @section.update_attributes(params[:section])
        format.html { redirect_to cms_section_path(@section), notice: 'Section was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cms/sections/1
  # DELETE /cms/sections/1.json
  def destroy
    @section = Section.find(params[:id])
    @section.destroy

    respond_to do |format|
      format.html { redirect_to cms_sections_url }
      format.json { head :ok }
    end
  end
end

jiehuo/app/controllers/cms/users_controller.rb
# coding: UTF-8
class Cms::UsersController < ApplicationController
  def index
    @users = User.where("school_id is not null")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end

  end

  # GET /cms/users/1
  # GET /cms/users/1.json
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /cms/users/new
  # GET /cms/users/new.json
  def new
    # @area = Area.all(:order => "name").map { |u| [u.name, u.id] }
    @province = get_redis_provinces().map { |u| [u["province"], u["provinceid"]] }
    @user = User.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /cms/users/1/edit
  def edit
    @province = get_redis_provinces().map { |u| [u["province"], u["provinceid"]] }
    @user = User.find(params[:id])
  end

  # POST /cms/users
  # POST /cms/users.json
  def create
    @user = User.new(params[:user])
    @province = get_redis_provinces().map { |u| [u["province"], u["provinceid"]] }
    respond_to do |format|
      if @user.save
        format.html { redirect_to cms_user_path(@user), notice: 'User was successfully created.' }
        format.json { render json: cms_user_path(@user), status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /cms/users/1
  # PUT /cms/users/1.json
  def update
    @province = get_redis_provinces().map { |u| [u["province"], u["provinceid"]] }
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to cms_user_path(@user), notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cms/users/1
  # DELETE /cms/users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

  def school_ajax
    province_id = params[:province_id]
    @schools = School.find_all_by_provinceid(province_id).map { |u| [u.name, u.id] };
    @province = get_redis_provinces().map { |u| [u["province"], u["provinceid"]] }
    respond_to do |format|
      format.js
    end
  end


end

jiehuo/app/helpers/cms/areas_helper.rb
module Cms::AreasHelper
end

jiehuo/app/helpers/cms/domains_helper.rb
module Cms::DomainsHelper

end

jiehuo/app/helpers/cms/projects_helper.rb
module Cms::ProjectsHelper
end

jiehuo/app/helpers/cms/schools_helper.rb
module Cms::SchoolsHelper
end

jiehuo/app/helpers/cms/sections_helper.rb
module Cms::SectionsHelper
end

jiehuo/app/helpers/cms/users_helper.rb
module Cms::UsersHelper
end

jiehuo/app/views/cms/users/_form.html.erb
# coding: UTF-8
<%= form_for([:cms, @user],:html => { :enctype =>  "multipart/form-data" }) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2> 注册时出现<%= pluralize(@user.errors.count, "") %> 个问题,亲！</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label "我的邮箱:" %>
      <%= f.text_field :email %>
    </div>
    <div class="field">

      <%= f.label "真实姓名:" %>
      <%= f.text_field :name %>
    </div>




    <div class="field">
    <%= f.label :avatar %>
    <%= image_tag(@user.avatar_url(:thumb)) if @user.avatar? %>
    <%= f.file_field :avatar %>
    </div>
    <% if (!@user.id) %>

        <div class="field">
          <%= f.label "密码:" %>
          <%= password_field "user", "password" %>
          <br/>

        </div>

        <div class="field">
          <%= f.label "确认密码:" %>

          <%= password_field "user", "password_confirmation" %>
          <br/>
        </div>
    <% end %>
    <% if @user.school
         school_name = @user.school.name
       else
         school_name = ""
       end
    %>
    <div class="field" id="matched_lawyer_list">
      <%= f.label "学校" %>   <%= select("educational", "xueli", {"小学" => "1", "中学" => "2", "大学" => "3"}) %>
      <input type="text" id = "school_code" name="school_code" value="<%= school_name %>">


      <%= hidden_field(:user, :school_id) %>
      <a id="school_select_btn" class="icon-sch txt-hidden" href="javascript:;">选择学校</a>
    </div>
    <div class="school_div">
      <div id="school_dialog" title="school dialog">
        <%= select(:area_edu, '', @province) %>
        <p></p>

        <div id="a_div">
          <div id="school_content">
          </div>
        </div>
      </div>

    </div>
    <div class="field">
      <%= f.label "自我介绍:" %>
      <br/>
      <%= f.text_area :introduce %>
    </div>
    <div class="actions">
      <%= f.submit "创建账号" %>
    </div>
<% end %>

<script>
    $(function () {
        $("#area_edu_").change(function () {
            $.ajax({
                type:"POST",
                url:"/cms/users/school_ajax",
                data:"province_id=" + this.value
            });
            return true;
        });
    })


    // increase the default animation speed to exaggerate the effect
    $.fx.speeds._default = 1000;

    $(function () {
        $("#school_dialog").dialog({
            autoOpen:false,
            show:"blind",
            hide:"explode"
        });

        $("#school_select_btn").click(function () {
            $("#school_dialog").dialog("open");
            $("#area_edu_").get(0).options[0].selected = true;
            $("#area_edu_").trigger("change");
            return false;
        });
    });


</script>

jiehuo/app/views/cms/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', cms_user_path(@user) %> |
<%= link_to 'Back', cms_users_path %>

jiehuo/app/views/cms/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>User</th>
    <th>Email</th>
    <th>Name</th>
    <th>学校</th>

    <th>Introduce</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.user_id %></td>
    <td><%= user.email %></td>
    <td><%= user.name %></td>
    <td> <%= user.school.name %> </td>


    <td><%= user.introduce %></td>

    <td><%= link_to 'Show', cms_user_path(user) %></td>
    <td><%= link_to 'Edit', edit_cms_user_path(user) %></td>
    <td><%= link_to 'Destroy', cms_user_path(user), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_cms_user_path %>

jiehuo/app/views/cms/users/login.html.erb
<form action="<%= url_for() %>" method="post" >

  登录成功！

</form>

jiehuo/app/views/cms/users/new.html.erb
<h1>我要注册:</h1>

<%= render 'form' %>

<%= link_to 'Back', cms_users_path %>

jiehuo/app/views/cms/users/school_ajax.js.erb
$("#school_content").remove();
var school_content_div = $('<div></div>');
school_content_div.attr('id', 'school_content');
<% i=0%>
<% @schools.each do  |n, value|    %>
<% i=i+1; %>
school_content_div.append("<a  id='school<%=value%>' name='<%=n%>' code='<%=value%>' > <%=n%>  </a>");
<% if(i%3==0) %>
school_content_div.append("<br>")
<% end %>
<% end %>
$("#a_div").append(school_content_div)


$(function () {
    $("#school_content a").click(function () {
            school_code_text_value = $(this).attr("name");
            $("#school_code").attr("value",school_code_text_value)  ;
            school_hidden_value =  $(this).attr("code");
            $("#user_school_id").attr("value",school_hidden_value);
            $("#school_dialog").dialog("close")
    });
});

jiehuo/app/views/cms/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user.user_id %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>



<p>
  <b>头像:</b>
  <%= image_tag(@user.avatar.thumb.url) if @user.avatar? %>
</p>


<p>
  <b>Introduce:</b>
  <%= @user.introduce %>
</p>




<%= link_to 'Edit', edit_cms_user_path(@user) %> |
<%= link_to 'Back', cms_users_path %>