jiehuo/config/routes.rb
Iknow::Application.routes.draw do



   #用户系统模块
  devise_for :users, :controllers => {:passwords => :devise_passwords,:invitations=>:devise_invitations,:sessions=>:devise_sessions} do
    #密码重置后跳转页面
    match '/users/password/reset_pw_success', :to => 'devise_passwords#reset_pw_success'
    #密码重置邮件发送成功后跳转页面
    match '/users/password/reset_pw_send_mail_ok', :to => 'devise_passwords#reset_pw_send_mail_ok'


  end

  #注册验证码路由
  captcha_route

  get "user_profile/basic"

  root :to => 'home#index'
  get "home/index"

  match '/follow/:id', :to => 'user_profile#follow#:id', :as => 'follow'
  match '/unfollow/:id', :to => 'user_profile#unfollow#:id', :as => 'unfollow'
  match '/unconcern/:id', :to => 'user_profile#unconcern#:id', :as => 'unconcern'
  match '/projects/follow/:id', :to => 'projects#follow#:id', :as => 'follow_project'
  match '/an_answer_comments/:id', :to => 'comments#an_answer_comments#:id', :as => 'comments'
  match '/people/follow_project/:project_id', :to => 'people#follow_project#:project_id', :as => 'people_follow_project'
  match '/people/unfollow_project/:project_id', :to => 'people#unfollow_project#:project_id', :as => 'people_unfollow_project'
  match '/people/collect_the_ask/:ask_id',:to=>'people#collect_the_ask#:ask_id',:as => 'people_collect_the_ask'
  match '/people/uncollect_the_ask/:ask_id',:to=>'people#uncollect_the_ask#:ask_id',:as => 'people_uncollect_the_ask'
  match '/people/add_as_classmate/:user_id',:to=>'people#add_as_classmate#:user_id',:as => 'people_add_as_classmate'
  match '/people/subtract_the_classmate/:user_id',:to=>'people#subtract_the_classmate#:user_id',:as => 'people_subtract_the_classmate'

  match '/register', :to => 'user_sessions#register'
  match '/user_profile/basic', :to => 'user_profile#basic'
  match '/user_profile/passwd', :to => 'user_profile#passwd'
  match '/user_profile/user_avatar', :to => 'user_profile#user_avatar'

  match '/people/more_set_asks/:ask_id/:id',:to=>'people#more_set_asks#:ask_id#:id'
  match '/people/more_answered_asks/:ask_id/:id',:to=>'people#more_answered_asks#:ask_id#:id'
  match '/people/more_favorites_asks/:ask_id/:id',:to=>'people#more_favorites_asks#:ask_id#:id'

  match '/people/answered_asks/:id',:to=>'people#answered_asks#:id'
  match '/people/favorites_asks/:id',:to=>'people#favorites_asks#:id'
  match '/ask/hide_ask/:id',:to=>'asks#hide_ask#:id'

  #match '/asks', :to => 'home#index'
  resources :comments, :answers, :asks
  resources :people
  resources :projects #网站端project模块

  resource :user_sessions, :member => {:register => :post}

  get "interest_users/get_interest_users"

  #CSM下的路由，这些路由进入网站后台
  namespace :cms do
    resources :domains, :schools, :projects, :sections
    resources :users do
      collection do
        post :school_ajax
      end
    end
  end

#-------------------------

#ask.js中使用到
  match ':controller(/:action(/:id(.:format)))'


end

jiehuo/app/models/person.rb
# encoding: utf-8
class Person
  attr_reader :following_projects #关注的学科

  attr_reader :user_base

  def initialize(user_id)
    @user_id = user_id
    @user_base = User.find_by_user_id(@user_id)
  end

  def school
    School.find_by_school_id(@user_base.school_id)
  end

  def area
    province = Province.find_by_provinceid(@user_base.provinceid)
    city = City.find_by_cityid(@user_base.cityid)
    return "应该不是地球的" if province.nil?
    return @area = province.province if city.nil?
    @area = province.province + " " + city.city
  end

  #关注的学科总数
  def following_projects_count
    FollowedProject.count(:conditions => ["user_id=?",@user_id])
  end

  def following_projects
    @following_projects = []
    User.find(@user_id).projects.each do |project|
      @following_projects << OneProject.new(project)
    end
    @following_projects
  end

  #收藏的问题总数
  def favorites_asks_count
    FavoriteAsk.count(:conditions => ["user_id = ?",@user_id])
  end

  #收藏考题列表
  def favorites_asks
    Ask.where("ask_id in (select ask_id from favorite_asks where user_id=#{@user_id})").order("created_at desc")
  end

  def get_favorites_asks_id_by_range(current_ask_id,page_size,index)
    FavoriteAsk.find_by_sql(["SELECT DISTINCT ask_id FROM favorite_asks WHERE (ask_id < ? and user_id=?) ORDER BY ask_id desc LIMIT ? OFFSET ?",current_ask_id,@user_id,page_size,page_size*index])
  end
  
  #关注Ta的同学数量
  def follower_count
    Follower.count(:conditions => ["be_follower_id = ?",@user_id])
  end

  #关注Ta的同学
  def followers
    User.find_by_sql(["select user_id,name,introduce,avatar from users WHERE user_id in (select follower_id from followers where be_follower_id = ?)",@user_id])
  end

  #Ta关注的同学数量
  def following_count
    Follower.count(:conditions => ["follower_id = ?",@user_id])
  end

  #Ta关注的同学
  def following
    User.find_by_sql(["select user_id,name,introduce,avatar from users WHERE user_id in (select be_follower_id from followers where follower_id = ?)",@user_id])
  end

  #出过题目的总数
  def set_asks_count
    Ask.count(:conditions => ["user_id = ? and state = 1",@user_id])
  end

  #出过的题目
  def set_asks
    Ask.all(:conditions => "asks.user_id=#{@user_id} and state = 1",:order => "created_at desc")
  end

  #根据给定的id取一个范围内的ID
  def get_set_asks_id_by_range(current_ask_id,page_size,index)
    Ask.where("ask_id< ? and asks.user_id=#{@user_id} and state = 1", current_ask_id).order("ask_id desc").limit(page_size).offset(page_size*index)
  end

  #答过题目的总数
  def answered_asks_count
    Answer.count_by_sql(["SELECT count(DISTINCT answers.ask_id) FROM answers,asks WHERE answers.user_id = ? and asks.ask_id = answers.ask_id and asks.state = 1",@user_id])
  end

  #答过的题目
  def answered_asks
    Answer.find_by_sql(["SELECT DISTINCT answers.ask_id FROM answers,asks WHERE answers.user_id = ? and asks.ask_id = answers.ask_id and asks.state = 1 order by ask_id desc",@user_id])
  end

  def get_answered_asks_id_by_range(current_ask_id,page_size,index)
    Answer.find_by_sql(["SELECT DISTINCT answers.ask_id FROM answers,asks WHERE (answers.ask_id < ? and answers.user_id=? and asks.ask_id = answers.ask_id and asks.state = 1) ORDER BY answers.ask_id desc LIMIT ? OFFSET ?",current_ask_id,@user_id,page_size,page_size*index])
  end

end

jiehuo/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  PAGE_SIZE = 5

  def show
    @person = Person.new(params[:id])
    @user_id = @person.user_base.user_id
    @current_user_id = current_user.id
    @following_projects_count = @person.following_projects_count
    @following_projects = @person.following_projects

    set_asks = asks_list(@person.set_asks[0...PAGE_SIZE])
    if set_asks.empty?
      @set_asks = []
      @last_ask_id = 0
    else
      @set_asks = set_asks
      @last_ask_id = @set_asks[set_asks.size-1].the_ask.ask_id
    end
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def more_set_asks
    @page_num = params[:pagenum].to_i

    @person = Person.new(params[:id])
    @set_asks = asks_list(@person.get_set_asks_id_by_range(params[:ask_id],PAGE_SIZE,@page_num))

    respond_to do |format|
      format.js # more_set_asks.js.erb
    end
  end

  def more_answered_asks
    @page_num = params[:pagenum].to_i
    @person = Person.new(params[:id])
    @answered_asks = asks_list(@person.get_answered_asks_id_by_range(params[:ask_id],PAGE_SIZE,@page_num))

    respond_to do |format|
      format.js # more_set_asks.js.erb
    end
  end

  def more_favorites_asks
    @page_num = params[:pagenum].to_i
    @person = Person.new(params[:id])
    @favorites_asks = asks_list(@person.get_favorites_asks_id_by_range(params[:ask_id],PAGE_SIZE,@page_num))

    respond_to do |format|
      format.js # more_set_asks.js.erb
    end
  end

  def answered_asks
    @person = Person.new(params[:id])
    @user_id = @person.user_base.user_id

    answered_asks = asks_list(@person.answered_asks[0...PAGE_SIZE])
    if answered_asks.empty?
      @answered_asks = []
      @last_ask_id = 0
    else
      @answered_asks = answered_asks
      @last_ask_id = @answered_asks[answered_asks.size-1].the_ask.ask_id

    end

    respond_to do |format|
      format.js #answered_asks.js.erb
      format.html # answered_asks.html.erb
    end
  end

  def favorites_asks
    @person = Person.new(params[:id])
    @user_id = @person.user_base.user_id
    @current_user_id = current_user.id

    favorites_asks = asks_list(@person.favorites_asks[0...PAGE_SIZE])
    if favorites_asks.empty?
      @favorites_asks = []
      @last_ask_id = 0
    else
      @favorites_asks = favorites_asks
      @last_ask_id = @favorites_asks[favorites_asks.size-1].the_ask.ask_id
    end
    respond_to do |format|
      format.js #answered_asks.js.erb
      format.html # answered_asks.html.erb
    end

  end

  def follow_project
    @followed_project = FollowedProject.new
    @followed_project.user_id = current_user.id
    @followed_project.project_id = params[:project_id]
    state = @followed_project.save

    if state.eql?(false)
      @error = @followed_project.errors
    end

    respond_to do |format|
      format.js
    end
  end

  def unfollow_project
    @state = false
    @followed_project = FollowedProject.first(:conditions => ["user_id=? and project_id=?",current_user.id,params[:project_id]])
    @state = @followed_project.destroy

    respond_to do |format|
      format.js
    end
  end

  def collect_the_ask
    @favorite_ask = FavoriteAsk.new
    @favorite_ask.user_id=current_user.id
    @favorite_ask.ask_id= params[:ask_id]
    state = @favorite_ask.save

    if state.eql?(false)
      @error = @favorite_ask.errors
    end

    respond_to do |format|
      format.js
    end
  end

  def uncollect_the_ask
    @favorite_ask = FavoriteAsk.first(:conditions => ["user_id=? and ask_id=?",current_user.id,params[:ask_id]])
    state = @favorite_ask.destroy

    if state.eql?(false)
      @error = @favorite_ask.errors
    end

    respond_to do |format|
      format.js
    end
  end

  def add_as_classmate
    @classmate = Follower.new
    @classmate.follower_id = current_user.id
    @classmate.be_follower_id= params[:user_id]
    if @classmate.save
      @state = true #保存成功
    else
      @state = false #保存失败
    end
  end

  def subtract_the_classmate
    @classmate = Follower.delete_all(:follower_id=>current_user.id,:be_follower_id=>params[:user_id])
  end

  private
  def asks_list(asks)
    asks_arr = []
    asks.each do |ask|
      asks_arr << OneAsk.new(ask.ask_id)
    end
    asks_arr
  end

end

jiehuo/app/helpers/people_helper.rb
# coding: utf-8
module PeopleHelper
  include AsksHelper

  def button_followed_project(user_id,project_id)
    if FollowedProject.exists?(:user_id=>user_id, :project_id=>project_id)
      raw "<a data-remote='true' href='/people/unfollow_project/#{project_id}'class='user_btn01' id='a_follow_link_#{project_id}'></a>"
    else
      raw "<a data-remote='true' href='/people/follow_project/#{project_id}' class='user_btn02' id='a_follow_link_#{project_id}'></a>"
    end
  end

  def a_favorite_ask(user_id,ask_id)
    if FavoriteAsk.exists?(:user_id=>user_id, :ask_id=>ask_id)
      raw "<a data-remote='true' href='/people/uncollect_the_ask/#{ask_id}' id='a_collect_ask_#{ask_id}'>取消收藏</a>"
    else
      raw "<a data-remote='true' href='/people/collect_the_ask/#{ask_id}' id='a_collect_ask_#{ask_id}'>收藏</a>"
    end
  end

  def show_project_asks_count(count)
     if count.nil?
       raw "还没有考题哦，去抢个沙发吧"
     else
       raw "在该学科下有#{count}道考题"
     end
  end

  def show_sex(person)
    if person.user_base.sex == "M" || person.user_base.sex == ""
      raw "<h3>学校：#{person.school.name}</h3>"
    else
      raw "<h2>学校：#{person.school.name}</h2>"
    end
  end

  def show_follow_button(user_id)
    if user_id != current_user.id
      if Follower.exists?(:follower_id=>current_user.id,:be_follower_id=>user_id)
        raw "<a data-remote='true' href='/people/subtract_the_classmate/#{user_id}' id='classmate_#{user_id}'><img border='0' src='/assets/btn27.jpg'></a>"#如果已关注，则显示取消关注按钮
      else
        raw "<a data-remote='true' class='jia' href='/people/add_as_classmate/#{user_id}' id='classmate_#{user_id}'><img border='0' src='/assets/btn18.jpg'></a>" #未关注，则显示加为同学按钮
      end
    end
  end

end

jiehuo/app/views/people/_followers.html.erb
<h1>关注TA的同学</h1>
<ul class="user_fans clearfix">
  <% followers.each do |follower| %>
    <li><a title="<%=follower.name %>" href="/people/<%=follower.user_id%>"><%= image_tag(follower.avatar_url(:min),:border=>"0")%></a></li>
  <% end %>
</ul>

jiehuo/app/views/people/_following_projects.html.erb
<h2>关注<span> <%=h @following_projects_count%> 门学科</span></h2>
<ul class="user_focus clearfix">
  <% following_projects.each do |project|%>
      <li>
        <div class="user_xk">
          <a href="/projects"><%=h project.project_base.name %></a>
          <br/><%= show_project_asks_count(project.asks_count) %>
        </div>
        <%= button_followed_project(@current_user_id,project.project_base.project_id)%>
      </li>
  <% end %>
</ul>

jiehuo/app/views/people/_followings.html.erb
<h1>TA关注的同学</h1>
<ul class="user_fans clearfix">
  <% followings.each do |follower| %>
      <li><a title="<%= h follower.name %>" href="/people/<%=follower.user_id%>"><%= image_tag(follower.avatar_url(:min),:border=>"0")%></a></li>
  <% end %>
</ul>

jiehuo/app/views/people/_set_asks.html.erb
    <div class="usert">
      <ul class="u_tit">
        <li class="u_first">出过(<%= h @person.set_asks_count %>)</li>
        <li><a href="javascript:void(0);" id="a_answered_asks">答过(<%= h @person.answered_asks_count %>)</a></li>
        <li><a href="javascript:void(0);" id="a_favorites_asks">收藏(<%= h @person.favorites_asks_count %>)</a></li>
      </ul>
    </div>
    <%if @set_asks.empty?%>
        TA还没有出过题目
    <%else%>
        <ul class="list_title clearfix" id="ul_set_asks">
          <% @set_asks.each do |ask| %>
              <%= render(:partial => 'ask', :object => ask) %>
          <% end %>
        </ul>
        <input type="hidden" name="page_num" value="0" id="page_num">
        <div class="listmore"><a href="javascript:void(0);" id="more_set_asks"><img src="/assets/more.jpg" border="0"/></a>
        </div>
    <%end%>

<script type="text/javascript">
    $(function () {
        $('#page_num').attr("value", 0);

        $("#more_set_asks").click(function () {
            var pagenum = Number($('#page_num').val());
            $.ajax({
                type:"get",
                url:"/people/more_set_asks/<%=h @last_ask_id%>/<%=h @user_id%>",
                data:"pagenum=" + pagenum,
                success:function () {
                    $('#page_num').attr("value", pagenum+1)
                }
            });
        });

        $("#a_answered_asks").click(function () {
            $.ajax({
                type:"get",
                url:"/people/answered_asks/<%=h @user_id%>",
                data:"pagenum=" + 0
            });
        });

        $("#a_favorites_asks").click(function () {
            $.ajax({
                type:"get",
                url:"/people/favorites_asks/<%=h @user_id%>",
                data:"pagenum=" + 0
            });
        });
    });
</script>

jiehuo/app/views/people/add_as_classmate.js.erb
<%if @state%>
var var_user_id = $("#hidden_user_id").val();
var var_url = "/people/subtract_the_classmate/"+var_user_id;
var selector = "#classmate_"+var_user_id;
$(selector).attr("href",var_url);
$(selector).html("<img border='0' src='/assets/btn27.jpg'>");
<%else%>
 alert("添加同学失败");
<%end%>

jiehuo/app/views/people/favorites_asks.js.erb
$('#asks_list').html("<%= j render :partial => "favorites_asks", :object => @favorites_asks %>");

jiehuo/app/views/people/more_answered_asks.js.erb
<%@answered_asks.each do |ask|%>
    $('#ul_answered_asks').append("<%= j render :partial => "ask", :object => ask %>");
<%end%>

jiehuo/app/views/people/more_asks.js.erb
alert("more_asks");

jiehuo/app/views/people/more_favorites_asks.js.erb
<%@favorites_asks.each do |ask|%>
$('#ul_favorites_asks').append("<%= j render :partial => "ask", :object => ask %>");
<%end%>

jiehuo/app/views/people/more_set_asks.js.erb
<%@set_asks.each do |ask|%>
  $('#ul_set_asks').append("<%= j render :partial => "ask", :object => ask %>");
<%end%>

jiehuo/app/views/people/show.html.erb
<div class="mid clearfix">
<div class="b_userbox">
  <div class="user_box1">
    <h1><%= image_tag(@person.user_base.avatar_url(:super_large),:border=>"0")%></h1>
    <ul class="usertitle1">
      <li>
        <div class="use_name1"><%=h @person.user_base.name%></div>
        <div class="jia_btn1">
            <%= show_follow_button(@person.user_base.user_id)%>
            <input type="hidden" id="hidden_user_id" value="<%=h @person.user_base.user_id%>">
        </div>
      </li>
      <li><%= show_sex(@person)%></li>

      <li>个人简介：<%=h @person.user_base.introduce%></li>
    </ul>
  </div>
  <ul class="b_f">
    <li>
      <div class="b_usertext"><span><%=h @person.follower_count%></span><br/>关注Ta的同学</div>
    </li>
    <li>
      <div class="b_usertext"><span><%=h @person.following_count%></span><br/>Ta关注的同学</div>
    </li>
  </ul>
</div>

<div class="left">
  <div class="tb_main" id="asks_list">
    <%= render(:partial =>'set_asks') if action_name == "show"%>
    <%= render(:partial =>'answered_asks') if action_name == "answered_asks"%>
    <%= render(:partial =>'favorites_asks') if action_name == "favorites_asks"%>
  </div>
</div>

<div class="right">
  <div class="xq1">
    <%= render(:partial =>'following_projects',:object => @following_projects) %>
  </div>

  <div class="xq">
    <%= render(:partial =>'followers',:object => @person.followers) %>
  </div>

  <div class="xq">
    <%= render(:partial =>'followings',:object => @person.following) %>
  </div>
</div>
</div>

jiehuo/app/views/people/subtract_the_classmate.js.erb
var var_user_id = $("#hidden_user_id").val();
var selector = "#classmate_"+var_user_id;
var var_url = "/people/add_as_classmate/"+var_user_id;
$(selector).attr("href",var_url);
$(selector).html("<img border='0' src='/assets/btn18.jpg'>");

jiehuo/app/views/people/uncollect_the_ask.js.erb
<% if @error%>
    alert("可能是数据出错了");
<%else%>
    var selector = "#a_collect_ask_"+<%=h @favorite_ask.ask_id%>
    $(selector).html("收藏");
    $(selector).attr("href","<%=people_collect_the_ask_path(@favorite_ask.ask_id)%>");
<%end%>

jiehuo/app/views/people/unfollow_project.js.erb
<% if @state.nil? %>
alert("出错，搞个样式");
<%else%>
   var selector = "#a_follow_link_"+<%=params[:project_id]%>
   $(selector).attr("class","user_btn02");
   $(selector).attr("href","/people/follow_project/"+<%=params[:project_id]%>);
<%end%>