jiehuo/config/routes.rb
Iknow::Application.routes.draw do



   #用户系统模块
  devise_for :users, :controllers => {:passwords => :devise_passwords,:invitations=>:devise_invitations,:sessions=>:devise_sessions} do
    #密码重置后跳转页面
    match '/users/password/reset_pw_success', :to => 'devise_passwords#reset_pw_success'
    #密码重置邮件发送成功后跳转页面
    match '/users/password/reset_pw_send_mail_ok', :to => 'devise_passwords#reset_pw_send_mail_ok'


  end

  #注册验证码路由
  captcha_route

  get "user_profile/basic"

  root :to => 'home#index'
  get "home/index"

  match '/follow/:id', :to => 'user_profile#follow#:id', :as => 'follow'
  match '/unfollow/:id', :to => 'user_profile#unfollow#:id', :as => 'unfollow'
  match '/unconcern/:id', :to => 'user_profile#unconcern#:id', :as => 'unconcern'
  match '/projects/follow/:id', :to => 'projects#follow#:id', :as => 'follow_project'
  match '/an_answer_comments/:id', :to => 'comments#an_answer_comments#:id', :as => 'comments'
  match '/people/follow_project/:project_id', :to => 'people#follow_project#:project_id', :as => 'people_follow_project'
  match '/people/unfollow_project/:project_id', :to => 'people#unfollow_project#:project_id', :as => 'people_unfollow_project'
  match '/people/collect_the_ask/:ask_id',:to=>'people#collect_the_ask#:ask_id',:as => 'people_collect_the_ask'
  match '/people/uncollect_the_ask/:ask_id',:to=>'people#uncollect_the_ask#:ask_id',:as => 'people_uncollect_the_ask'
  match '/people/add_as_classmate/:user_id',:to=>'people#add_as_classmate#:user_id',:as => 'people_add_as_classmate'
  match '/people/subtract_the_classmate/:user_id',:to=>'people#subtract_the_classmate#:user_id',:as => 'people_subtract_the_classmate'

  match '/register', :to => 'user_sessions#register'
  match '/user_profile/basic', :to => 'user_profile#basic'
  match '/user_profile/passwd', :to => 'user_profile#passwd'
  match '/user_profile/user_avatar', :to => 'user_profile#user_avatar'

  match '/people/more_set_asks/:ask_id/:id',:to=>'people#more_set_asks#:ask_id#:id'
  match '/people/more_answered_asks/:ask_id/:id',:to=>'people#more_answered_asks#:ask_id#:id'
  match '/people/more_favorites_asks/:ask_id/:id',:to=>'people#more_favorites_asks#:ask_id#:id'

  match '/people/answered_asks/:id',:to=>'people#answered_asks#:id'
  match '/people/favorites_asks/:id',:to=>'people#favorites_asks#:id'
  match '/ask/hide_ask/:id',:to=>'asks#hide_ask#:id'

  #match '/asks', :to => 'home#index'
  resources :comments, :answers, :asks
  resources :people
  resources :projects #网站端project模块

  resource :user_sessions, :member => {:register => :post}

  get "interest_users/get_interest_users"

  #CSM下的路由，这些路由进入网站后台
  namespace :cms do
    resources :domains, :schools, :projects, :sections
    resources :users do
      collection do
        post :school_ajax
      end
    end
  end

#-------------------------

#ask.js中使用到
  match ':controller(/:action(/:id(.:format)))'


end

jiehuo/app/models/answer.rb
class Answer < ActiveRecord::Base
  self.set_primary_key :answer_id
  belongs_to :user
  belongs_to :ask
  has_many :comments

  def self.user_answers_count(answer)
    user_id_key = answer.user_id
    $redis.zincrby("user_answers_count", 1, user_id_key)
  end

end

jiehuo/app/controllers/answers_controller.rb
# coding: UTF-8
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    redirect_to "/home/index"
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    #@answer = Answer.find(params[:id])
    redirect_to "/home/index"
    #respond_to do |format|
      #format.html # show.html.erb
      #format.json { render json: @answer }
    #end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    #@answer = Answer.new
    redirect_to "/home/index"
   # respond_to do |format|
      #format.html # new.html.erb
      #format.json { render json: @answer }
    #end
  end

  # GET /answers/1/edit
  def edit
    redirect_to "/home/index"
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])
    @answer.user_id=current_user.id
    @answer.modifier=current_user.id

    if params.has_key?(:multiple)
      @answer.result=""
      params[:multiple].each_value do |value|
        @answer.result= @answer.result + " "+ value
      end
    end

    respond_to do |format|
      if @answer.save
        Answer.user_answers_count(@answer)
        ask_answers_count @answer.ask_id
        project_ask_count @answer.ask_id
        if (!@answer.comment.blank?)
          ask_comments_count @answer.ask_id
        end
        @one_answer = OneAnswer.new(@answer)
        @state = "OK"
        format.js
      else
        @state = "Error"
        format.js
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    #@answer = Answer.find(params[:id])
    redirect_to "/home/index"
    #respond_to do |format|
      #if @answer.update_attributes(params[:answer])
        #format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        #format.json { head :ok }
      #else
        #format.html { render action: "edit" }
        #format.json { render json: @answer.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    redirect_to "/home/index"
  end

  #问题的解答次数统计  做+1
  def ask_answers_count ask_id
    ask_id_key = ask_id.to_s
    $redis.zincrby($ask_answers_count_rank, 1, ask_id_key)
    # 1000
  end

  #问题 解题思路的次数统计 做+1

  def ask_comments_count ask_id
    ask_id_key = ask_id.to_s
    $redis.zincrby($ask_comments_count_rank, 1, ask_id_key)
  end

  #解答问题时,以对应的学科redis常量+project_id为key,以问题id为member 做+1
  def project_ask_count ask_id
    ask = Ask.find_by_ask_id ask_id
    project_id = ask.project_id
    key = $redis_interest_ask_project+project_id.to_s
    ask_count = $redis.zscore($ask_answers_count_rank, ask_id.to_s)
    $redis.zadd(key, ask_count, ask_id.to_s)
  end


end

jiehuo/app/helpers/answers_helper.rb
module AnswersHelper
end

jiehuo/app/views/answers/_an_answer.html.erb
<li>
  <div class="an_stem">
    <div class="an_answer">
      <div class="an_user"><a href="<%=h person_path(an_answer.owner.user_id)%>"><%=h an_answer.owner.name %>: </a><%=h truncate(an_answer.owner.introduce,:length => 30) %></div>
      <h1>答案</h1>
      <ul class="an_checklist">
        <li><%=jiehuo_simple_format h an_answer.the_answer.result%></li>
      </ul>
    </div>
    <div class="an_tou"><a href="javascript:void(0);" title="<%= h an_answer.owner.name %>"><%= image_tag(an_answer.owner.avatar_url(:mid))%></a></div>
    <div class="an_bc0">
      <h1>思路</h1>
      <h2><%=jiehuo_simple_format h an_answer.the_answer.comment%></h2>
    </div>
    <div class="an_com">
      <%=h an_answer.the_answer.created_at.strftime("%F %T")%>
      <a onclick="get_comments(this)" href="javascript:void(0);" id="a_comments_<%=h an_answer.the_answer.answer_id.to_s%>">
        <%=h an_answer.comments_count%>条评论
      </a>
    </div>

    <div id="comments_answer_<%=h an_answer.the_answer.answer_id%>" class="an_quebox clearfix">
    </div>
  </div>
</li>

<script type="text/javascript">

    function get_comments(val){
        var answer_id = val.id.substr(11);
        var div_selector = "#comments_answer_"+answer_id;
        //判断如果comments_answer_X层下存在其他层，清空存在的层
        if($(div_selector+":has(div)").length>0){
            $(div_selector).empty();
        }else{
            //判断如果comments_answer_X层下不存在其他层，则提交AJAX请求
            $.ajax({
                type:"get",
                url:"/an_answer_comments/"+answer_id
            });
        }
    }
</script>

jiehuo/app/views/answers/create.js.erb
<%if @state == "OK"%>
  $("#last_answer").before('<%= j render(:partial =>'answers/an_answer',:object=>@one_answer) %>');
  $("#answer_comment_textarea").attr("value","");
  $(":checkbox").attr("checked",false);
  $(":radio").attr("checked",false);
  $("#answer_result_saq").attr("value","");
<%else%>
    alert("答案保存失败");
<%end%>