jiehuo/config/routes.rb
Iknow::Application.routes.draw do



   #用户系统模块
  devise_for :users, :controllers => {:passwords => :devise_passwords,:invitations=>:devise_invitations,:sessions=>:devise_sessions} do
    #密码重置后跳转页面
    match '/users/password/reset_pw_success', :to => 'devise_passwords#reset_pw_success'
    #密码重置邮件发送成功后跳转页面
    match '/users/password/reset_pw_send_mail_ok', :to => 'devise_passwords#reset_pw_send_mail_ok'


  end

  #注册验证码路由
  captcha_route

  get "user_profile/basic"

  root :to => 'home#index'
  get "home/index"

  match '/follow/:id', :to => 'user_profile#follow#:id', :as => 'follow'
  match '/unfollow/:id', :to => 'user_profile#unfollow#:id', :as => 'unfollow'
  match '/unconcern/:id', :to => 'user_profile#unconcern#:id', :as => 'unconcern'
  match '/projects/follow/:id', :to => 'projects#follow#:id', :as => 'follow_project'
  match '/an_answer_comments/:id', :to => 'comments#an_answer_comments#:id', :as => 'comments'
  match '/people/follow_project/:project_id', :to => 'people#follow_project#:project_id', :as => 'people_follow_project'
  match '/people/unfollow_project/:project_id', :to => 'people#unfollow_project#:project_id', :as => 'people_unfollow_project'
  match '/people/collect_the_ask/:ask_id',:to=>'people#collect_the_ask#:ask_id',:as => 'people_collect_the_ask'
  match '/people/uncollect_the_ask/:ask_id',:to=>'people#uncollect_the_ask#:ask_id',:as => 'people_uncollect_the_ask'
  match '/people/add_as_classmate/:user_id',:to=>'people#add_as_classmate#:user_id',:as => 'people_add_as_classmate'
  match '/people/subtract_the_classmate/:user_id',:to=>'people#subtract_the_classmate#:user_id',:as => 'people_subtract_the_classmate'

  match '/register', :to => 'user_sessions#register'
  match '/user_profile/basic', :to => 'user_profile#basic'
  match '/user_profile/passwd', :to => 'user_profile#passwd'
  match '/user_profile/user_avatar', :to => 'user_profile#user_avatar'

  match '/people/more_set_asks/:ask_id/:id',:to=>'people#more_set_asks#:ask_id#:id'
  match '/people/more_answered_asks/:ask_id/:id',:to=>'people#more_answered_asks#:ask_id#:id'
  match '/people/more_favorites_asks/:ask_id/:id',:to=>'people#more_favorites_asks#:ask_id#:id'

  match '/people/answered_asks/:id',:to=>'people#answered_asks#:id'
  match '/people/favorites_asks/:id',:to=>'people#favorites_asks#:id'
  match '/ask/hide_ask/:id',:to=>'asks#hide_ask#:id'

  #match '/asks', :to => 'home#index'
  resources :comments, :answers, :asks
  resources :people
  resources :projects #网站端project模块

  resource :user_sessions, :member => {:register => :post}

  get "interest_users/get_interest_users"

  #CSM下的路由，这些路由进入网站后台
  namespace :cms do
    resources :domains, :schools, :projects, :sections
    resources :users do
      collection do
        post :school_ajax
      end
    end
  end

#-------------------------

#ask.js中使用到
  match ':controller(/:action(/:id(.:format)))'


end

jiehuo/app/models/domain.rb
class Domain < ActiveRecord::Base
    self.set_primary_key :domain_id
    has_many :projects
end

jiehuo/app/controllers/cms/domains_controller.rb
# coding: UTF-8
class Cms::DomainsController < ApplicationController
  # GET /cms/domains
  # GET /cms/domains.json
  def index
    @cms_domains = Domain.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cms_domains }
    end
  end

  # GET /cms/domains/1
  # GET /cms/domains/1.json
  def show
    @cms_domain = Domain.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cms_domain }
    end
  end

  # GET /cms/domains/new
  # GET /cms/domains/new.json
  def new
    @cms_domain = Domain.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cms_domain }
    end
  end

  # GET /cms/domains/1/edit
  def edit
    @cms_domain = Domain.find(params[:id])
  end

  # POST /cms/domains
  # POST /cms/domains.json
  def create

    @cms_domain = Domain.new(params[:domain])#A此地cms_domain修改为domain

    respond_to do |format|
      if @cms_domain.save
        format.html { redirect_to cms_domain_path(@cms_domain), notice: 'Domain was successfully created.' } #A此地@cms_domain修改为cms_domain_path(@cms_domain)
        format.json { render json: @cms_domain, status: :created, location: @cms_domain }
      else
        format.html { render action: "new" }
        format.json { render json: @cms_domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cms/domains/1
  # PUT /cms/domains/1.json
  def update
    @cms_domain = Domain.find(params[:id])

    respond_to do |format|
      if @cms_domain.update_attributes(params[:domain])#A此地cms_domain修改为domain
        format.html { redirect_to cms_domain_path, notice: 'Domain was successfully updated.' } #A此地@cms_domain修改为cms_domain_path
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cms_domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cms/domains/1
  # DELETE /cms/domains/1.json
  def destroy
    @cms_domain = Domain.find(params[:id])
    @cms_domain.destroy

    respond_to do |format|
      format.html { redirect_to cms_domains_url }
      format.json { head :ok }
    end
  end
end

jiehuo/app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @domains }
    end
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    @domain = Domain.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @domain }
    end
  end

  # GET /domains/new
  # GET /domains/new.json
  def new
    @domain = Domain.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @domain }
    end
  end

  # GET /domains/1/edit
  def edit
    @domain = Domain.find(params[:id])
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(params[:domain])

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render json: @domain, status: :created, location: @domain }
      else
        format.html { render action: "new" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /domains/1
  # PUT /domains/1.json
  def update
    @domain = Domain.find(params[:id])

    respond_to do |format|
      if @domain.update_attributes(params[:domain])
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy

    respond_to do |format|
      format.html { redirect_to domains_url }
      format.json { head :ok }
    end
  end
end

jiehuo/app/helpers/cms/domains_helper.rb
module Cms::DomainsHelper

end

jiehuo/app/helpers/domains_helper.rb
module DomainsHelper
end

jiehuo/app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :creator %><br />
    <%= f.text_field :creator %>
  </div>
  <div class="field">
    <%= f.label :modifier %><br />
    <%= f.text_field :modifier %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jiehuo/app/views/domains/edit.html.erb
<h1>Editing domain</h1>

<%= render 'form' %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

jiehuo/app/views/domains/index.html.erb
<h1>Listing domains</h1>

<table>
  <tr>
    <th>Domain</th>
    <th>Name</th>
    <th>Description</th>
    <th>Creator</th>
    <th>Modifier</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @domains.each do |domain| %>
  <tr>
    <td><%= domain.domain_id %></td>
    <td><%= domain.name %></td>
    <td><%= domain.description %></td>
    <td><%= domain.creator %></td>
    <td><%= domain.modifier %></td>
    <td><%= link_to 'Show', domain %></td>
    <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
    <td><%= link_to 'Destroy', domain, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Domain', new_domain_path %>

jiehuo/app/views/domains/new.html.erb
<h1>New domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

jiehuo/app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Domain:</b>
  <%= @domain.domain_id %>
</p>

<p>
  <b>Name:</b>
  <%= @domain.name %>
</p>

<p>
  <b>Description:</b>
  <%= @domain.description %>
</p>

<p>
  <b>Creator:</b>
  <%= @domain.creator %>
</p>

<p>
  <b>Modifier:</b>
  <%= @domain.modifier %>
</p>


<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>